name: PetClinic CI/CD

on:
  push:
    branches: [prod]
  workflow_dispatch:

jobs:
  build:
    name: Build, Test, Scan & Push
    runs-on: ubuntu-latest
    timeout-minutes: 45
    permissions:
      contents: read
    steps:
        - name: checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Setup JDK
          uses: actions/setup-java@v6
          with:
            distribution: temurin
            java-version: '21'
        - name: Sonar Analysis
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          run: |
              mvn -B verify sonar:sonar \
              -Dsonar.host.url="$SONAR_HOST_URL" \
              -Dsonar.token="$SONAR_TOKEN" \
              -Dsonar.oraganization-bootcamp1 \
              -Dsonar.projectKey=myown-springbootapp \
              -Dsonar.projectName=myown-springbootapp \
              -Dsonar.java.binaries=target/classes \
              -Dsonar.qualitygate.timeout=300
